version: '3'
services:
  react: # 컨테이너 이름 지정 
    build: 
      context: . # context: 도커 이미지를 구성하기 위한 파일과 폴더들이 있는 위치 (도커파일이 있는 위치)
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true # 리액트 앱을 끌때 필요 (리액트 한정)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm", "run", "test"]